Test commit
oracoolsss/net pull request #1
Opened 2020-09-21 14:37 UTC by oracoolsss

Hello, @Aloomenon

2020-09-24 12:41 UTC, Aloomenon commented
отличный код. А теперь засуньте его весь в пулл реквест.

2020-10-20 15:52 UTC, oracoolsss commented
@Aloomenon

2020-10-25 08:56 UTC, Aloomenon requested changes

2020-10-25 08:56 UTC, Aloomenon commented on lab1/src/com/Main.java
> +    private final static String MESSAGE = "Test";
Если это весь код, то я не вижу кроме констант ничего.

2020-10-25 08:56 UTC, Aloomenon commented on lab2/server/src/ClientHandler.java
> +        if (fileSize == (new File(RECEIVE_FILES_PATH + fileName)).length()) {
считаете это корректной проверкой на целостность файла?

2020-10-25 08:56 UTC, Aloomenon commented on lab2/client/src/Client.java
> +            in.close();
в каком случае не закроются ресурсы?

2020-11-11 15:31 UTC, oracoolsss commented on lab2/server/src/ClientHandler.java
> +        if (fileSize == (new File(RECEIVE_FILES_PATH + fileName)).length()) {
я бы это назвал минимальной проверкой

2020-11-11 15:34 UTC, oracoolsss commented
@Aloomenon, теперь в lab1 fixed полностью лабораторная 1 исправленная лежит, весь код видно

2020-11-11 15:58 UTC, oracoolsss commented on lab2/client/src/Client.java
> +            in.close();
если JVM упадет до их закрытия

2020-11-14 09:19 UTC, Aloomenon commented
Ок. Фамилию и имя скажите.

2020-11-14 13:07 UTC, oracoolsss commented
> Ок. Фамилию и имя скажите.

Черновский Степан

2021-01-24 13:12 UTC, closed without merging