lab3
oracoolsss/net pull request #2
Opened 2020-11-10 11:58 UTC by oracoolsss

Сделал 3 лабу

2020-11-11 15:34 UTC, oracoolsss commented
@Aloomenon

2020-11-14 09:18 UTC, Aloomenon requested changes
Почитайте про освобождение ресурсов и многопоточность в Java.
По возможности сократите кол-во потоков и Job до 1-го.

Раскажите как работает Vector в многопоточной среде.

2020-11-14 09:18 UTC, Aloomenon commented on lab3/src/com/oracoolsss/DatagramWrapper.java
> +        this.message = deserializeObject(datagramPacket.getData());
Какая кодировка?

2020-11-14 09:18 UTC, Aloomenon commented on lab3/src/com/oracoolsss/Message.java
> +        REGISTER_MESSAGE,
Зачем?

2020-12-29 13:08 UTC, oracoolsss commented on lab3/src/com/oracoolsss/Message.java
> +        REGISTER_MESSAGE,
Вспомнил, что вы говорили так не делать, убрал

2020-12-29 13:11 UTC, oracoolsss commented on lab3/src/com/oracoolsss/DatagramWrapper.java
> +        this.message = deserializeObject(datagramPacket.getData());
На моей JVM UTF-8, проверил с помощью defaultCharset()

2020-12-29 13:28 UTC, oracoolsss commented
> Раскажите как работает Vector в многопоточной среде.

Vector - потокобезопасная коллекция, соответственно, можно использовать при работе с несколькими потоками. Он является synchronized, то есть в один момент времени с ним может работать только один поток

2020-12-29 16:02 UTC, Aloomenon approved these changes
Вроде похоже на правду. Принял

2021-01-24 13:13 UTC, closed without merging